require_relative '../Abomination/abomination'
require_relative '../Binary Mobile/binary_mobile'
require_relative '../Caesar Cipher/caesar_cipher'
require_relative '../Homogenize/homogenize'
require_relative '../Longest Sequence/longest_sequence'
require_relative '../Magic Square/magic_square'
require_relative '../Monochrome Bitmaps/monochrome_bitmaps'
require_relative '../Music Collection/music_collection'
require_relative '../Object thread/object_thread'
require_relative '../Partition/partition'
require_relative '../Robot/robot'
require_relative '../To Proc/to_proc'
require_relative '../Zigzag/zigzag'
