require_relative '../Magic Square/magic_square'
require_relative '../Caesar Cipher/caesar_cipher'
require_relative '../Music Collection/music_collection'
require_relative '../Binary Mobile/binary_mobile'
require_relative '../Monochrome Bitmaps/monochrome_bitmaps'
