require_relative '../Abomination/abomination'
require_relative '../Binary Mobile/binary_mobile'
require_relative '../Caesar Cipher/caesar_cipher'
require_relative '../Magic Square/magic_square'
require_relative '../Monochrome Bitmaps/monochrome_bitmaps'
require_relative '../Music Collection/music_collection'
require_relative '../Robot/robot'
require_relative '../Zigzag/zigzag'
